uint32_t fill_text_buffer(char* s, TextChar* buffer, Vec2f position)
{
	uint32_t i = 0;
	while(s[i] != '\0')
	{
		int32_t char_index;
		switch(s[i])
		{
			case ' ': char_index = 0; break;
			case '!': char_index = 1; break;
			case '"': char_index = 2; break;
			case '#': char_index = 3; break;
			case '$': char_index = 4; break;
			case '%': char_index = 5; break;
			case '&': char_index = 6; break;
			case '\'': char_index = 7; break;
			case '(': char_index = 8; break;
			case ')': char_index = 9; break;
			case '*': char_index = 10; break;
			case '+': char_index = 11; break;
			case ',': char_index = 12; break;
			case '-': char_index = 13; break;
			case '.': char_index = 14; break;
			case '/': char_index = 15; break;
			case '0': char_index = 16; break;
			case '1': char_index = 17; break;
			case '2': char_index = 18; break;
			case '3': char_index = 19; break;
			case '4': char_index = 20; break;
			case '5': char_index = 21; break;
			case '6': char_index = 22; break;
			case '7': char_index = 23; break;
			case '8': char_index = 24; break;
			case '9': char_index = 25; break;
			case ':': char_index = 26; break;
			case ';': char_index = 27; break;
			case '<': char_index = 28; break;
			case '=': char_index = 29; break;
			case '>': char_index = 30; break;
			case '?': char_index = 31; break;
			case '@': char_index = 32; break;
			case 'A': char_index = 33; break;
			case 'B': char_index = 34; break;
			case 'C': char_index = 35; break;
			case 'D': char_index = 36; break;
			case 'E': char_index = 37; break;
			case 'F': char_index = 38; break;
			case 'G': char_index = 39; break;
			case 'H': char_index = 40; break;
			case 'I': char_index = 41; break;
			case 'J': char_index = 42; break;
			case 'K': char_index = 43; break;
			case 'L': char_index = 44; break;
			case 'M': char_index = 45; break;
			case 'N': char_index = 46; break;
			case 'O': char_index = 47; break;
			case 'P': char_index = 48; break;
			case 'Q': char_index = 49; break;
			case 'R': char_index = 50; break;
			case 'S': char_index = 51; break;
			case 'T': char_index = 52; break;
			case 'U': char_index = 53; break;
			case 'V': char_index = 54; break;
			case 'W': char_index = 55; break;
			case 'X': char_index = 56; break;
			case 'Y': char_index = 57; break;
			case 'Z': char_index = 58; break;
			case '[': char_index = 59; break;
			case '\\': char_index = 60; break;
			case ']': char_index = 61; break;
			case '^': char_index = 62; break;
			case '_': char_index = 63; break;
			case '`': char_index = 64; break;
			case 'a': char_index = 65; break;
			case 'b': char_index = 66; break;
			case 'c': char_index = 67; break;
			case 'd': char_index = 68; break;
			case 'e': char_index = 69; break;
			case 'f': char_index = 70; break;
			case 'g': char_index = 71; break;
			case 'h': char_index = 72; break;
			case 'i': char_index = 73; break;
			case 'j': char_index = 74; break;
			case 'k': char_index = 75; break;
			case 'l': char_index = 76; break;
			case 'm': char_index = 77; break;
			case 'n': char_index = 78; break;
			case 'o': char_index = 79; break;
			case 'p': char_index = 80; break;
			case 'q': char_index = 81; break;
			case 'r': char_index = 82; break;
			case 's': char_index = 83; break;
			case 't': char_index = 84; break;
			case 'u': char_index = 85; break;
			case 'v': char_index = 86; break;
			case 'w': char_index = 87; break;
			case 'x': char_index = 88; break;
			case 'y': char_index = 89; break;
			case 'z': char_index = 90; break;
			case '{': char_index = 91; break;
			case '|': char_index = 92; break;
			case '}': char_index = 93; break;
			case '~': char_index = 94; break;
			default: char_index = 0;
		}
		buffer[i] = (TextChar){char_index, position.x + i, position.y};
		i++;
	}
	return i;
}
